using System;

namespace FastdfsMonitor.Models
{
    public class FastDFSStatus
    {
        public string IpAddress { get; set; }
        public int Port { get; set; }
        public DateTime CurrentTime { get; set; }
        public TimeSpan RunningTime { get; set; }
        public int ThreadPoolSize { get; set; }
        public int ThreadPoolCurrentThreads { get; set; }
        public int ThreadPoolIdleThreads { get; set; }
        public int ConnectionPoolSize { get; set; }
        public int ConnectionPoolCurrentConnections { get; set; }
        public int ConnectionPoolIdleConnections { get; set; }
        public StorageNode[] StorageNodes { get; set; }
        public int UploadQueueSize { get; set; }
        public int DownloadQueueSize { get; set; }
        public int DeleteQueueSize { get; set; }
        public long UploadCount { get; set; }
        public long DownloadCount { get; set; }
        public long DeleteCount { get; set; }
        public long TotalUploadBytes { get; set; }
        public long TotalDownloadBytes { get; set; }
        public long TotalUploadFiles { get; set; }
        public long TotalAppendBytes { get; set; }
        public long TotalModifyBytes { get; set; }
        public long TotalTruncateCount { get; set; }
        public long TotalTruncateBytes { get; set; }
        public long TotalFetchCount { get; set; }
        public long TotalFetchBytes { get; set; }
        public long TotalSyncInBytes { get; set; }
        public long TotalSyncOutBytes { get; set; }
        public long TotalFileOpenCount { get; set; }
        public long TotalFileReadCount { get; set; }
        public long TotalFileWriteCount { get; set; }
        public long TotalFileCloseCount { get; set; }
        public long TotalFileUnlinkCount { get; set; }
        public long TotalFileStatCount { get; set; }
        public long TotalFileSyncCount { get; set; }
        public long TotalFileFlushCount { get; set; }
        public long TotalFileFsyncCount { get; set; }
        public long TotalFileLockCount { get; set; }
        public long TotalFileUnlockCount { get; set; }
        public long TotalFileGetMetadataCount { get; set; }
        public long TotalFileSetMetadataCount { get; set; }
        public long TotalFileTruncateCount { get; set; }
        public long TotalFileUploadCount { get; set; }
        public long TotalFileAppendCount { get; set; }
        public long TotalFileModifyCount { get; set; }
        public long TotalFileFetchCount { get; set; }
        public long TotalFileDownloadCount { get; set; }
        public long TotalFileHitCount { get; set; }
        public long TotalFileStorageCount { get; set; }
        public long TotalFileSyncInCount { get; set; }
        public long TotalFileSyncOutCount { get; set; }
        public long TotalFileQueueCount { get; set; }
        public long TotalSyncSrcInBytes { get; set; }
        public long TotalSyncDestInBytes { get; set; }
        public long TotalSyncSrcOutBytes { get; set; }

        public string Version { get; set; }
        public string GroupName { get; set; }
        public long TotalUploadCount { get; set; }
        public long TotalAppendCount { get; set; }
        public long TotalModifyCount { get; set; }

        public long TotalDownloadCount { get; set; }
        public long TotalSyncInCount { get; set; }
        public long TotalSyncOutCount { get; set; }
        public long TotalFilePreadCount { get; set; }
        public long TotalFilePwriteCount { get; set; }
        public long TotalFileDioReadCount { get; set; }
        public long TotalFileDioWriteCount { get; set; }
        public long TotalFileDioSyncCount { get; set; }
        public long TotalFileDioAsyncCount { get; set; }
        public long TotalFileDioSyncWaitCount { get; set; }
        public long TotalFileDioAsyncWaitCount { get; set; }
        public long TotalFileDioAsyncBytes { get; set; }
        public long TotalTrunkCount { get; set; }
        public long TotalStorageCount { get; set; }
        public long TotalCurrentTrunkCount { get; set; }
        public long TotalCurrentStorageCount { get; set; }
        public long TotalStorePathCount { get; set; }
        public long TotalSubdirCountPerPath { get; set; }
        public long TotalCurrentWritePath { get; set; }
        public long TotalDiskCount { get; set; }
        public long TotalReadOnlyCount { get; set; }
        public long TotalActiveCount { get; set; }
        public long TotalFsyncCount { get; set; }
        public long TotalStoragePortCount { get; set; }
        public long TotalStorageHttpPortCount { get; set; }
        public long TotalStorageHttpsPortCount { get; set; }
        public long TotalStorageSyncPortCount { get; set; }
        public long TotalStorageSyncHttpsPortCount { get; set; }
        public long TotalStorageBeatCount { get; set; }
        public long TotalStorageBeatBytes { get; set; }
        public long TotalStorageJoinCount { get; set; }
        public long TotalStorageJoinBytes { get; set; }
        public long TotalStorageAliveCount { get; set; }
        public long TotalStorageDeadCount { get; set; }
        public long TotalStorageReplCount { get; set; }
        public long TotalStorageReplBytes { get; set; }
        public long TotalStorageBadCount { get; set; }
        public long TotalStorageBusyCount { get; set; }
        public long TotalStorageDelCount { get; set; }
        public long TotalStorageDownloadCount { get; set; }
        public long TotalStorageUploadCount { get; set; }
        public long TotalSuccessUploadCount { get; set; }
        public long TotalFileResendCount { get; set; }
        public long TotalFileSyncInSuccessCount { get; set; }
        public long TotalFileSyncOutSuccessCount { get; set; }
        public long TotalFileCompareCount { get; set; }
        public long TotalFileCompareFailCount { get; set; }
        public long TotalFileEliminateCount { get; set; }
        public long TotalSrcFileCount { get; set; }
        public long TotalSyncSrcFileCount { get; set; }
        public long TotalSyncDstFileCount { get; set; }
        public long TotalSyncSameFileCount { get; set; }
        public long TotalSyncDiffFileCount { get; set; }
        public long TotalSyncSkipSrcSameFileCount { get; set; }
        public long TotalSyncSkipSrcDiffFileCount { get; set; }
        public long TotalSyncSkipDstSameFileCount { get; set; }
        public long TotalSyncSkipDstDiffFileCount { get; set; }
        public long TotalSyncDstFileExistCount { get; set; }
        public long TotalSyncDstFileExistSkipCount { get; set; }
        public long TotalSyncInDelayCount { get; set; }
        public long TotalSyncOutDelayCount { get; set; }
        public long TotalSyncInFailCount { get; set; }
        public long TotalSyncOutFailCount { get; set; }
        public long TotalSyncInSize { get; set; }
        public long TotalSyncOutSize { get; set; }
        public long TotalSyncInFileCount { get; set; }
        public long TotalSyncOutFileCount { get; set; }
        public long TotalSyncSkipInSameFileCount { get; set; }
        public long TotalSyncSkipInDiffFileCount { get; set; }
        public long TotalSyncSkipOutSameFileCount { get; set; }
        public long TotalSyncSkipOutDiffFileCount { get; set; }
        public long TotalSyncSrcOtherErrCount { get; set; }
        public long TotalSyncDstOtherErrCount { get; set; }
        public long TotalSyncRenameCount { get; set; }
        public long TotalSyncCpFileCount { get; set; }
        public long TotalSyncDelFileCount { get; set; }
        public long TotalSyncTruncFileCount { get; set; }
        public long TotalFileSyncSkipCount { get; set; }
        public long TotalFileSyncSameFileCount { get; set; }
        public long TotalFileSyncSkipSrcSameFileCount { get; set; }
        public long TotalFileSyncSkipSrcDiffFileCount { get; set; }
        public long TotalFileSyncSkipDstSameFileCount { get; set; }
        public long TotalFileSyncSkipDstDiffFileCount { get; set; }
        public long TotalFileSyncSkipNotMySelfCount { get; set; }
        public long TotalFileSyncDoneCount { get; set; }
        public long TotalFileDiffCount { get; set; }
        public long TotalSetMetaCount { get; set; }
        public long TotalDeleteCount { get; set; }
        public long TotalFileOpenNanos { get; set; }
        public long TotalFileReadNanos { get; set; }
        public long TotalFileWriteNanos { get; set; }
        public long TotalFileFlushNanos { get; set; }
        public long TotalFileSyncNanos { get; set; }
        public long TotalFilePreadNanos { get; set; }
        public long TotalFilePwriteNanos { get; set; }
        public long TotalFileSyncInNanos { get; set; }
        public long TotalFileSyncOutNanos { get; set; }
        public long TotalFileDioReadNanos { get; set; }

        public long TotalFileDioWriteNanos { get; set; }
        public long TotalServerCount { get; set; }
        public long TotalAliveServerCount { get; set; }
        public long TotalDeadServerCount { get; set; }
        public long TotalCurrentWriteServerCount { get; set; }
        public long TotalCurrentReadServerCount { get; set; }
        public long TotalSubdirCount { get; set; }
        public long TotalCurrentWritePathCount { get; set; }
        public long TotalCurrentTrunkFreeSpace { get; set; }
        public long TotalStorageServerCount { get; set; }
        public long TotalStorageServerOnlineCount { get; set; }
        public long TotalStorageServerOfflineCount { get; set; }
        public long TotalStorageServerActiveCount { get; set; }
        public long TotalStorageServerCurrentWriteCount { get; set; }
        public long TotalStorageServerStorePathCount { get; set; }
        public long TotalStorageServerSubdirCount { get; set; }
        public long TotalStorageServerCurrentWritePathCount { get; set; }
        public long TotalStorageServerTotalUploadCount { get; set; }
        public long TotalStorageServerSuccessUploadCount { get; set; }
        public long TotalStorageServerTotalAppendCount { get; set; }
        public long TotalStorageServerSuccessAppendCount { get; set; }
        public long TotalStorageServerTotalModifyCount { get; set; }
        public long TotalStorageServerSuccessModifyCount { get; set; }
        public long TotalStorageServerTotalTruncateCount { get; set; }
        public long TotalStorageServerSuccessTruncateCount { get; set; }
        public long TotalStorageServerTotalSetMetaCount { get; set; }
        public long TotalStorageServerSuccessSetMetaCount { get; set; }
        public long TotalStorageServerTotalDeleteCount { get; set; }
        public long TotalStorageServerSuccessDeleteCount { get; set; }
        public long TotalStorageServerTotalDownloadCount { get; set; }
        public long TotalStorageServerSuccessDownloadCount { get; set; }
        public long TotalStorageServerTotalGetMetaCount { get; set; }
        public long TotalStorageServerSuccessGetMetaCount { get; set; }
        public long TotalStorageServerTotalCreateLinkCount { get; set; }
        public long TotalStorageServerSuccessCreateLinkCount { get; set; }
        public long TotalStorageServerTotalDeleteLinkCount { get; set; }
        public long TotalStorageServerSuccessDeleteLinkCount { get; set; }
        public long TotalStorageServerTotalUploadBytes { get; set; }
        public long TotalStorageServerSuccessUploadBytes { get; set; }
        public long TotalStorageServerTotalAppendBytes { get; set; }
        public long TotalStorageServerSuccessAppendBytes { get; set; }
        public long TotalStorageServerTotalModifyBytes { get; set; }
        public long TotalStorageServerSuccessModifyBytes { get; set; }
        public long TotalStorageServerTotalDownloadBytes { get; set; }
        public long TotalStorageServerSuccessDownloadBytes { get; set; }
        public long TotalStorageServerLastSourceUpdate { get; set; }
        public long TotalStorageServerLastSyncUpdate { get; set; }
        public long TotalStorageServerLastSyncedTimestamp { get; set; }
        public long TotalTrackerServerCount { get; set; }
        public long TotalTrackerServerOnlineCount
        {
            get; set;
        }
        public long TotalTrackerServerOfflineCount { get; set; }
        public long TotalTrackerServerActiveCount { get; set; }
        public long TotalTrackerServerTotalSetCount { get; set; }
        public long TotalTrackerServerSuccessSetCount { get; set; }
        public long TotalTrackerServerTotalGetCount { get; set; }
        public long TotalTrackerServerSuccessGetCount { get; set; }
        public long TotalTrackerServerTotalDeleteCount { get; set; }
        public long TotalTrackerServerSuccessDeleteCount { get; set; }
        public long TotalTrackerServerTotalUpdateCount { get; set; }
        public long TotalTrackerServerSuccessUpdateCount { get; set; }
        public long TotalTrackerServerTotalCreateLinkCount { get; set; }
        public long TotalTrackerServerSuccessCreateLinkCount { get; set; }
        public long TotalTrackerServerTotalDeleteLinkCount { get; set; }
        public long TotalTrackerServerSuccessDeleteLinkCount { get; set; }
        public long TotalTrackerServerTotalGetMetaCount { get; set; }
        public long TotalTrackerServerSuccessGetMetaCount { get; set; }
        public long TotalTrackerServerTotalHeartbeatCount { get; set; }
        public long TotalTrackerServerSuccessHeartbeatCount { get; set; }
        public long TotalTrackerServerTotalUpdateStateCount { get; set; }
        public long TotalTrackerServerSuccessUpdateStateCount { get; set; }
        public long TotalTrackerServerTotalSyncInCount { get; set; }
        public long TotalTrackerServerSuccessSyncInCount { get; set; }
        public long TotalTrackerServerTotalSyncOutCount { get; set; }
        public long TotalTrackerServerSuccessSyncOutCount { get; set; }
        public long TotalTrackerServerTotalTransferCount { get; set; }
        public long TotalTrackerServerSuccessTransferCount { get; set; }
        public long TotalTrackerServerTotalQueryAndUpdateCount { get; set; }
        public long TotalTrackerServerSuccessQueryAndUpdateCount { get; set; }
        public long TotalTrackerServerTotalCreateStorageCount { get; set; }
        public long TotalTrackerServerSuccessCreateStorageCount { get; set; }
        public long TotalTrackerServerTotalDeleteStorageCount { get; set; }
        public long TotalTrackerServerSuccessDeleteStorageCount { get; set; }
        public long TotalTrackerServerTotalGetDataSizeCount { get; set; }
        public long TotalTrackerServerSuccessGetDataSizeCount { get; set; }
        public long TotalTrackerServerTotalGetGroupsCount { get; set; }
        public long TotalTrackerServerSuccessGetGroupsCount { get; set; }
        public long TotalTrackerServerTotalGetStorageCount { get; set; }
        public long TotalTrackerServerSuccessGetStorageCount { get; set; }
        public long TotalTrackerServerTotalGetMetadataCount { get; set; }
        public long TotalTrackerServerSuccessGetMetadataCount { get; set; }
        public long TotalTrackerServerTotalSetMetadataCount { get; set; }
        public long TotalTrackerServerSuccessSetMetadataCount { get; set; }
        public long TotalTrackerServerTotalSetStorageCount { get; set; }
        public long TotalTrackerServerSuccessSetStorageCount { get; set; }
        public long TotalTrackerServerTotalGetStorageInfoCount { get; set; }
        public long TotalTrackerServerSuccessGetStorageInfoCount { get; set; }
        public long TotalTrackerServerTotalGetServerIdCount { get; set; }
        public long TotalTrackerServerSuccessGetServerIdCount { get; set; }
        public long TotalTrackerServerTotalDoLeaderCount { get; set; }
        public long TotalTrackerServerSuccessDoLeaderCount { get; set; }
        public long TotalTrackerServerTotalGetLeaderCount { get; set; }
        public long TotalTrackerServerSuccessGetLeaderCount { get; set; }
        public long TotalTrackerServerTotalDirectStoreCount { get; set; }
        public long TotalTrackerServerSuccessDirectStoreCount { get; set; }
        public long TotalTrackerServerTotalDirectQueryCount { get; set; }
        public long TotalTrackerServerSuccessDirectQueryCount { get; set; }
        public long TotalStorageServerCurrentWriteServerCount { get; set; }
        public long TotalStorageServerCurrentReadOnlyServerCount { get; set; }
        public long TotalStorageServerTotalSyncInBytes { get; set; }
        public long TotalStorageServerSuccessSyncInBytes { get; set; }
        public long TotalStorageServerTotalSyncOutBytes { get; set; }
        public long TotalStorageServerSuccessSyncOutBytes { get; set; }
        public long TotalStorageServerTotalFileOpenCount { get; set; }
        public long TotalStorageServerSuccessFileOpenCount { get; set; }
        public long TotalStorageServerTotalFileReadCount { get; set; }
        public long TotalStorageServerSuccessFileReadCount { get; set; }
        public long TotalStorageServerTotalFileWriteCount
        { get; set; }
        public long TotalStorageServerSuccessFileWriteCount { get; set; }
        public long TotalStorageServerTotalFileCloseCount { get; set; }
        public long TotalStorageServerSuccessFileCloseCount { get; set; }
        public long TotalStorageServerTotalFileUnlinkCount { get; set; }
        public long TotalStorageServerSuccessFileUnlinkCount { get; set; }
        public long TotalStorageServerTotalFileStatCount { get; set; }
        public long TotalStorageServerSuccessFileStatCount { get; set; }
        public long TotalStorageServerTotalFileListCount { get; set; }
        public long TotalStorageServerSuccessFileListCount { get; set; }
        public long TotalStorageServerTotalFileSyncInCount { get; set; }
        public long TotalStorageServerSuccessFileSyncInCount { get; set; }
        public long TotalStorageServerTotalFileSyncOutCount { get; set; }
        public long TotalStorageServerSuccessFileSyncOutCount { get; set; }
        public long TotalStorageServerTotalRejectCount { get; set; }
        public long TotalStorageServerTotalServerCount { get; set; }
        public long TotalStorageServerSuccessServerCount { get; set; }
        public long TotalStorageServerTotalPingCount { get; set; }
        public long TotalStorageServerSuccessPingCount { get; set; }
        public long TotalStorageServerTotalGetGroupCount { get; set; }
        public long TotalStorageServerSuccessGetGroupCount { get; set; }
        public long TotalStorageServerTotalGetTotalSizeCount { get; set; }
        public long TotalStorageServerSuccessGetTotalSizeCount { get; set; }
        public long TotalStorageServerTotalGetFreeSizeCount { get; set; }
        public long TotalStorageServerSuccessGetFreeSizeCount { get; set; }
        public long TotalStorageServerTotalDeleteStorageCount { get; set; }
        public long TotalStorageServerSuccessDeleteStorageCount { get; set; }
        public long TotalStorageServerTotalSetTrunkServerCount { get; set; }
        public long TotalStorageServerSuccessSetTrunkServerCount { get; set; }
        public long TotalStorageServerTotalGetTrunkServerCount { get; set; }
        public long TotalStorageServerSuccessGetTrunkServerCount { get; set; }
        public long TotalStorageServerTotalReportCidCount { get; set; }
        public long TotalStorageServerSuccessReportCidCount { get; set; }
        public long TotalStorageServerTotalFetchOneCount { get; set; }
        public long TotalStorageServerSuccessFetchOneCount { get; set; }
        public long TotalStorageServerTotalPushOneCount { get; set; }
        public long TotalStorageServerSuccessPushOneCount { get; set; }
        public long TotalStorageServerTotalPackCount { get; set; }
        public long TotalStorageServerSuccessPackCount { get; set; }
        public long TotalStorageServerTotalBatchAppendCount { get; set; }
        public long TotalStorageServerSuccessBatchAppendCount { get; set; }
        public long TotalStorageServerTotalBatchModifyCount { get; set; }
        public long TotalStorageServerSuccessBatchModifyCount { get; set; }
        public long TotalStorageServerTotalBatchDeleteCount { get; set; }
        public long TotalStorageServerSuccessBatchDeleteCount { get; set; }
        public long TotalStorageServerTotalBatchSetMetaCount { get; set; }
        public long TotalStorageServerSuccessBatchSetMetaCount { get; set; }
    } 
 }

    
