namespace FastdfsMonitor.Models
{
    public class StorageNode
    {
        public string IpAddress { get; set; }
        public int Port { get; set; }
        public string GroupName { get; set; }
        public bool Active { get; set; }
        public long TotalStorageMB { get; set; }
        public long FreeStorageMB { get; set; }
        public long UploadPriority { get; set; }
        public long DownloadPriority { get; set; }
        public long StorePathCount { get; set; }
        public long SubdirCountPerPath { get; set; }
        public long CurrentWritePath { get; set; }
        public long TotalUploadBytes { get; set; }
        public long TotalAppendBytes { get; set; }
        public long TotalModifyBytes { get; set; }
        public long TotalTruncateCount { get; set; }
        public long TotalTruncateBytes { get; set; }
        public long TotalFetchCount { get; set; }
        public long TotalFetchBytes { get; set; }
        public long TotalSyncInBytes { get; set; }
        public long TotalSyncOutBytes { get; set; }
        public long TotalFileOpenCount { get; set; }
        public long TotalFileReadCount { get; set; }
        public long TotalFileWriteCount { get; set; }
        public long TotalFileCloseCount { get; set; }
        public long TotalFileUnlinkCount { get; set; }
        public long TotalFileStatCount { get; set; }
        public long TotalFileSyncCount { get; set; }
        public long TotalFileFlushCount { get; set; }
        public long TotalFileFsyncCount { get; set; }
        public long TotalFileLockCount { get; set; }
        public long TotalFileUnlockCount { get; set; }
        public long TotalFileGetMetadataCount { get; set; }
        public long TotalFileSetMetadataCount { get; set; }
        public long TotalFileTruncateCount { get; set; }
        public long TotalFileUploadCount { get; set; }
        public long TotalFileAppendCount { get; set; }
        public long TotalFileModifyCount { get; set; }
        public long TotalFileFetchCount { get; set; }
        public long TotalFileDownloadCount { get; set; }
        public long TotalFileHitCount { get; set; }
        public long TotalFileStorageCount { get; set; }
        public long TotalFileSyncInCount { get; set; }
        public long TotalFileSyncOutCount { get; set; }
        public long TotalFileQueueCount { get; set; }
        public long TotalSyncSrcInBytes { get; set; }
        public long TotalSyncDestInBytes { get; set; }
        public long TotalSyncSrcOutBytes { get; set; }
        public long TotalSyncDestOutBytes { get; set; }
        public long TotalAppenderCount { get; set; }
        public long TotalTrunkFallocCount { get; set; }
        public long TotalTrunkFreallocCount { get; set; }
        public long TotalTrunkFreeCount { get; set; }
        public long TotalTrunkBusyCount { get; set; }
        public long TotalTrunkOndiskCount { get; set; }
        public long TotalTrunkOnmemCount { get; set; }

        public long TotalInodeCount { get; set; }
        public long TotalInodeUsedCount { get; set; }
        public long TotalInodeFreeCount { get; set; }
        public long TotalInodeUsagePercent { get; set; }
        public long TotalInodeMaxCount { get; set; }
        public long TotalInodeMaxUsagePercent { get; set; }
        public long TotalMB { get; set; }
        public long TotalUsedMB { get; set; }
        public long TotalFreeMB { get; set; }
        public long TotalUsagePercent { get; set; }
        public long TotalMaxMB { get; set; }
        public long TotalMaxUsagePercent { get; set; }
        public long TotalUploadCount { get; set; }
        public long TotalAppendCount { get; set; }
        public long TotalModifyCount { get; set; }
        public long TotalDownloadCount { get; set; }
        public long TotalSyncInCount { get; set; }
        public long TotalSyncOutCount { get; set; }
        public long TotalFilePreadCount { get; set; }
        public long TotalFilePwriteCount { get; set; }
        public long TotalFileDioReadCount { get; set; }
        public long TotalFileDioWriteCount { get; set; }
        public long TotalFileDioSyncCount { get; set; }
        public long TotalFileDioAsyncCount { get; set; }
        public long TotalFileDioAsyncBytes { get; set; }
        public long TotalFileReadTime { get; set; }
        public long TotalFileWriteTime { get; set; }
        public long TotalFileDioReadTime { get; set; }
        public long TotalFileDioWriteTime { get; set; }
        public long TotalSyncInTime { get; set; }
        public long TotalSyncOutTime { get; set; }
        public long TotalFirstRoundTripTime { get; set; }
        public long TotalNextRoundTripTime { get; set; }
        public long TotalPreadTime { get; set; }
        public long TotalPwriteTime { get; set; }
        public long TotalFileOpenTime { get; set; }
        public long TotalFileStatTime { get; set; }
        public long TotalFileLockTime { get; set; }
        public long TotalFileFlushTime { get; set; }
        public long TotalFileSyncTime { get; set; }
        public long TotalFileDioReadSpeed { get; set; }
        public long TotalFileDioWriteSpeed { get; set; }
        public long TotalFileDioReadMaxTime { get; set; }
        public long TotalFileDioWriteMaxTime { get; set; }
        public long TotalFileDioReadMisCount { get; set; }
        public long TotalFileDioWriteMisCount { get; set; }
        public long TotalTrunkFileSize { get; set; }
        public long TotalTrunkFreeSpace { get; set; }
        public long TotalTrunkPeerCount { get; set; }
        public long TotalTrunkFileSizePercent { get; set; }
        public long TotalTrunkFreeSpacePercent { get; set; }
    }

}
